import {
  Box,
  Divider,
  Heading,
  Link,
  List,
  ListItem,
  Text,
  UnorderedList,
  VStack,
} from "@chakra-ui/react";

const PrivacyPolicy = () => {
  return (
    <Box maxW="7xl" mx="auto" p={4}>
      <VStack spacing={6} align="flex-start">
        <Heading as="h1" size="xl">
          Privacy Policy for Aarti Multi Services
        </Heading>
        <Text fontSize="md" color="gray.600">
          Last updated: July 31, 2024
        </Text>
        <Text>
          This Privacy Policy describes Our policies and procedures on the
          collection, use and disclosure of Your information when You use the
          Service and tells You about Your privacy rights and how the law
          protects You.
        </Text>
        <Text>
          We use Your Personal data to provide and improve the Service. By using
          the Service, You agree to the collection and use of information in
          accordance with this Privacy Policy.
        </Text>

        <Heading as="h2" size="lg" mt={8}>
          Interpretation
        </Heading>
        <Text>
          The words of which the initial letter is capitalized have meanings
          defined under the following conditions. The following definitions
          shall have the same meaning regardless of whether they appear in
          singular or in plural.
        </Text>

        <Heading as="h3" size="md" mt={6}>
          Definitions
        </Heading>
        <Text>For the purposes of this Privacy Policy:</Text>
        <List spacing={3} pl={4}>
          <ListItem>
            <strong>Account</strong> means a unique account created for You to
            access our Service or parts of our Service.
          </ListItem>
          <ListItem>
            <strong>Affiliate</strong> means an entity that controls, is
            controlled by or is under common control with a party, where
            &quot;control&quot; means ownership of 50% or more of the shares,
            equity interest or other securities entitled to vote for election of
            directors or other managing authority.
          </ListItem>
          <ListItem>
            <strong>Company</strong> (referred to as either &quot;the
            Company&quot;, &quot;We&quot;, &quot;Us&quot; or &quot;Our&quot; in
            this Agreement) refers to Aarti Multi Services Private Limited, Flat
            no. 101, Prathamesh PLaza, Unthkhana Rood, Above Peter England
            Showroom, Medical square, Nagpur-09.
          </ListItem>
          <ListItem>
            <strong>Cookies</strong> are small files that are placed on Your
            computer, mobile device or any other device by a website, containing
            the details of Your browsing history on that website among its many
            uses.
          </ListItem>
          <ListItem>
            <strong>Country</strong> refers to: Maharashtra, India
          </ListItem>
          <ListItem>
            <strong>Device</strong> means any device that can access the Service
            such as a computer, a cellphone or a digital tablet.
          </ListItem>
          <ListItem>
            <strong>Personal Data</strong> is any information that relates to an
            identified or identifiable individual.
          </ListItem>
          <ListItem>
            <strong>Service</strong> refers to the Website.
          </ListItem>
          <ListItem>
            <strong>Service Provider</strong> means any natural or legal person
            who processes the data on behalf of the Company. It refers to
            third-party companies or individuals employed by the Company to
            facilitate the Service, to provide the Service on behalf of the
            Company, to perform services related to the Service or to assist the
            Company in analyzing how the Service is used.
          </ListItem>
          <ListItem>
            <strong>Usage Data</strong> refers to data collected automatically,
            either generated by the use of the Service or from the Service
            infrastructure itself (for example, the duration of a page visit).
          </ListItem>
          <ListItem>
            <strong>Website</strong> refers to Aarti Multi Services, accessible
            from www.aartimultiservices.com
          </ListItem>
          <ListItem>
            <strong>You</strong> means the individual accessing or using the
            Service, or the company, or other legal entity on behalf of which
            such individual is accessing or using the Service, as applicable.
          </ListItem>
        </List>

        <Heading as="h3" size="md" mt={6}>
          Collecting and Using Your Personal Data
        </Heading>
        <Text>Types of Data Collected</Text>
        <List spacing={3} pl={4}>
          <ListItem>
            <strong>Personal Data</strong>: Email address, first name and last
            name, phone number, address, and other personally identifiable
            information.
          </ListItem>
          <ListItem>
            <strong>Usage Data</strong>:{" "}
            <Text>
              Usage Data is collected automatically when using the Service.
            </Text>
            <Text>
              Usage Data may include information such as Your Device&apos;s
              Internet Protocol address (e.g. IP address), browser type, browser
              version, the pages of our Service that You visit, the time and
              date of Your visit, the time spent on those pages, unique device
              identifiers and other diagnostic data.
            </Text>
            <Text>
              When You access the Service by or through a mobile device, We may
              collect certain information automatically, including, but not
              limited to, the type of mobile device You use, Your mobile device
              unique ID, the IP address of Your mobile device, Your mobile
              operating system, the type of mobile Internet browser You use,
              unique device identifiers and other diagnostic data.
            </Text>
          </ListItem>
        </List>

        <Box p={6} maxW="3xl" mx="auto">
      <Heading as="h2" size="xl" mb={4}>
        Tracking Technologies and Cookies
      </Heading>
      <Text mb={4}>
        We use Cookies and similar tracking technologies to track the activity on Our Service and store certain information.
        Tracking technologies used are beacons, tags, and scripts to collect and track information and to improve and analyze Our Service. The technologies We use may include:
      </Text>
      
      <UnorderedList spacing={3} mb={4}>
        <ListItem>
          <strong>Cookies or Browser Cookies:</strong> A cookie is a small file placed on Your Device. You can instruct Your browser to refuse all Cookies or to indicate when a Cookie is being sent. However, if You do not accept Cookies, You may not be able to use some parts of our Service. Unless you have adjusted Your browser setting so that it will refuse Cookies, our Service may use Cookies.
        </ListItem>
        <ListItem>
          <strong>Web Beacons:</strong> Certain sections of our Service and our emails may contain small electronic files known as web beacons (also referred to as clear gifs, pixel tags, and single-pixel gifs) that permit the Company, for example, to count users who have visited those pages or opened an email and for other related website statistics (for example, recording the popularity of a certain section and verifying system and server integrity).
        </ListItem>
      </UnorderedList>

      <Text mb={4}>
        Cookies can be "Persistent" or "Session" Cookies. Persistent Cookies remain on Your personal computer or mobile device when You go offline, while Session Cookies are deleted as soon as You close Your web browser. Learn more about cookies on the Free Privacy Policy website article.
      </Text>

      <Heading as="h3" size="lg" mb={4}>
        We use both Session and Persistent Cookies for the purposes set out below:
      </Heading>

      <UnorderedList spacing={3} mb={4}>
        <ListItem>
          <strong>Necessary / Essential Cookies</strong>
          <UnorderedList spacing={2}>
            <ListItem><strong>Type:</strong> Session Cookies</ListItem>
            <ListItem><strong>Administered by:</strong> Us</ListItem>
            <ListItem><strong>Purpose:</strong> These Cookies are essential to provide You with services available through the Website and to enable You to use some of its features. They help to authenticate users and prevent fraudulent use of user accounts. Without these Cookies, the services that You have asked for cannot be provided, and We only use these Cookies to provide You with those services.</ListItem>
          </UnorderedList>
        </ListItem>
        
        <ListItem>
          <strong>Cookies Policy / Notice Acceptance Cookies</strong>
          <UnorderedList spacing={2}>
            <ListItem><strong>Type:</strong> Persistent Cookies</ListItem>
            <ListItem><strong>Administered by:</strong> Us</ListItem>
            <ListItem><strong>Purpose:</strong> These Cookies identify if users have accepted the use of cookies on the Website.</ListItem>
          </UnorderedList>
        </ListItem>

        <ListItem>
          <strong>Functionality Cookies</strong>
          <UnorderedList spacing={2}>
            <ListItem><strong>Type:</strong> Persistent Cookies</ListItem>
            <ListItem><strong>Administered by:</strong> Us</ListItem>
            <ListItem><strong>Purpose:</strong> These Cookies allow us to remember choices You make when You use the Website, such as remembering your login details or language preference. The purpose of these Cookies is to provide You with a more personal experience and to avoid You having to re-enter your preferences every time You use the Website.</ListItem>
          </UnorderedList>
        </ListItem>
      </UnorderedList>

      <Text mb={4}>
        For more information about the cookies we use and your choices regarding cookies, please visit our{' '}
        <Link href="/cookies-policy" color="teal.500">Cookies Policy</Link> or the Cookies section of our Privacy Policy.
      </Text>
    </Box>

        <Heading as="h3" size="md" mt={6}>
          Use of Your Personal Data
        </Heading>
        <Text>
          The Company may use Personal Data for the following purposes...
        </Text>
        <List spacing={3} pl={4}>
          <ListItem>To provide and maintain our Service.</ListItem>
          <ListItem>To manage Your Account and registration.</ListItem>
          <ListItem>For the performance of a contract.</ListItem>
          <ListItem>To contact You regarding updates or information.</ListItem>
        </List>

        <Heading as="h3" size="md" mt={6}>
          Retention of Your Personal Data
        </Heading>
        <Text>
          The Company will retain Your Personal Data only for as long as is
          necessary for the purposes set out in this Privacy Policy...
        </Text>

        <Heading as="h3" size="md" mt={6}>
          Transfer of Your Personal Data
        </Heading>
        <Text>
          Your information, including Personal Data, is processed at the
          Company's operating offices and may be transferred to countries with
          different data protection laws...
        </Text>

        <Heading as="h3" size="md" mt={6}>
          Delete Your Personal Data
        </Heading>
        <Text>
          You have the right to delete or request assistance in deleting the
          Personal Data that We have collected about You...
        </Text>

        <Heading as="h3" size="md" mt={6}>
          Disclosure of Your Personal Data
        </Heading>
        <Text>
          Under certain circumstances, the Company may be required to disclose
          Your Personal Data by law or in response to valid requests by public
          authorities...
        </Text>

        <Heading as="h3" size="md" mt={6}>
          Security of Your Personal Data
        </Heading>
        <Text>
          The security of Your Personal Data is important to Us, but no method
          of transmission or storage is 100% secure...
        </Text>

        <Heading as="h3" size="md" mt={6}>
          Children's Privacy
        </Heading>
        <Text>Our Service does not address anyone under the age of 13...</Text>

        <Heading as="h3" size="md" mt={6}>
          Links to Other Websites
        </Heading>
        <Text>
          Our Service may contain links to other websites that are not operated
          by Us...
        </Text>

        <Heading as="h3" size="md" mt={6}>
          Changes to this Privacy Policy
        </Heading>
        <Text>
          We may update Our Privacy Policy from time to time. We will notify You
          of any changes...
        </Text>

        <Heading as="h3" size="md" mt={6}>
          Contact Us
        </Heading>
        <Text>
          If you have any questions about this Privacy Policy, You can contact
          us at:
        </Text>
        <List spacing={3} pl={4}>
          <ListItem>
            Email:{" "}
            <Link href="mailto:support@aartimultiservices.com">
              support@aartimultiservices.com
            </Link>
          </ListItem>
          <ListItem>
            Website:{" "}
            <Link href="https://www.aartimultiservices.com/contact">
              www.aartimultiservices.com/contact
            </Link>
          </ListItem>
          <ListItem>Phone: 0712-2766651</ListItem>
          <ListItem>
            Mail: Flat no. 101, Prathamesh PLaza, Unthkhana Rood, Above Peter
            England Showroom, Medical square, Nagpur-09
          </ListItem>
        </List>
      </VStack>
    </Box>
  );
};

export default PrivacyPolicy;
